feat: register hooks for deploy/undeploy time event registration
adobe/aio-cli-plugin-events pull request #56
Opened 2023-05-09 12:40 UTC by sangeetha5491

## Description

Hooks are stubbed, and just output part of the config they are passed
Pre-deploy-event hooks filter out registrations of journal type and create/update the registrations for the same based on information from the .aio file.
Post-deploy-event hooks filter out registrations of webhook type ( runtime actions ) and create/update the registrations for the same based on information from the .aio file.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-06-20 01:06 UTC, purplecabbage requested changes
A few small changes around `process` use.

2023-06-20 01:06 UTC, purplecabbage commented on src/hooks/utils/hook-utils.js
> +const process = require('process')
you don't need to define process either, you can just use it

2023-06-20 01:06 UTC, purplecabbage commented on src/hooks/utils/hook-utils.js
> +  if (!process.env.AIO_events_providermetadata_to_provider_mapping) {
isn't AIO_events_providermetadata_to_provider_mapping already part of the passed config?  I would rather not have every lib/plugin/hook looking for their own process.env vars as it will be a mess to maintain.  If this is not passed currently, we should make it so it is.

2023-06-20 17:59 UTC, sangeetha5491 commented on src/hooks/utils/hook-utils.js
> +  if (!process.env.AIO_events_providermetadata_to_provider_mapping) {
I dont think we pass the env variable AIO_events_providermetadata_to_provider_mapping: https://github.com/adobe/aio-cli-plugin-app/pull/678/files#diff-d8a2f401e6b0d2b5fd5984fc6dfafe2a18773cb8453a31fbbc4830d78d2095f7R123

2023-06-27 13:51 UTC, purplecabbage approved these changes

2023-06-27 19:20 UTC, merged